"""add order fields

Revision ID: 7a2b9ccd6c45
Revises: 24368f6a92c9
Create Date: 2026-04-10 22:29:09.441758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2b9ccd6c45'
down_revision = '24368f6a92c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('commission', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('customer_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('customer_phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_order_order_number'), ['order_number'], unique=True)
        batch_op.create_foreign_key(None, 'sales_invoice', ['invoice_id'], ['id'])

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_order_order_number'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('customer_phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('customer_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('notes')
        batch_op.drop_column('commission')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
